In [1]:
from numpy import loadtxt

In [5]:
from keras.models import Sequential

In [4]:
from keras.layers import Dense

In [6]:
dataset = loadtxt('pima-indians-diabetes.csv', delimiter=',')

In [7]:
X = dataset[:,0:8]

In [8]:
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [10]:
Y = dataset[:,8]

In [23]:
Y

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 0., 0., 0.

In [11]:
model = Sequential()

In [13]:
model.add(Dense(12, input_dim=8, activation='relu'))

In [14]:
model.add(Dense(8, activation='relu'))

In [15]:
model.add(Dense(1, activation='sigmoid'))

In [16]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [17]:
model.fit(X, Y, epochs=150, batch_size=10)_, accuracy = model.evaluate(X, y)

Epoch 1/150
768/768 [==============================] - 2s 2ms/step - loss: 1.3737 - acc: 0.5299
Epoch 2/150
768/768 [==============================] - 0s 595us/step - loss: 0.7345 - acc: 0.6289
Epoch 3/150
768/768 [==============================] - 0s 541us/step - loss: 0.6766 - acc: 0.6393
Epoch 4/150
768/768 [==============================] - 0s 537us/step - loss: 0.6657 - acc: 0.6380
Epoch 5/150
768/768 [==============================] - 0s 504us/step - loss: 0.6607 - acc: 0.6341
Epoch 6/150
768/768 [==============================] - 0s 519us/step - loss: 0.6563 - acc: 0.6445
Epoch 7/150
768/768 [==============================] - 0s 539us/step - loss: 0.6536 - acc: 0.6432
Epoch 8/150
768/768 [==============================] - 0s 517us/step - loss: 0.6482 - acc: 0.6497
Epoch 9/150
768/768 [==============================] - 0s 538us/step - loss: 0.6473 - acc: 0.6536
Epoch 10/150
768/768 [==============================] - 0s 534us/step - loss: 0.6404 - acc: 0.6576
Epoch 11/150
768/768 

768/768 [==============================] - 0s 557us/step - loss: 0.5991 - acc: 0.6602
Epoch 84/150
768/768 [==============================] - 0s 556us/step - loss: 0.5959 - acc: 0.6680
Epoch 85/150
768/768 [==============================] - 1s 669us/step - loss: 0.5964 - acc: 0.6693
Epoch 86/150
768/768 [==============================] - 0s 602us/step - loss: 0.5938 - acc: 0.6719
Epoch 87/150
768/768 [==============================] - 0s 567us/step - loss: 0.5934 - acc: 0.6745
Epoch 88/150
768/768 [==============================] - 0s 617us/step - loss: 0.5918 - acc: 0.6693
Epoch 89/150
768/768 [==============================] - 0s 587us/step - loss: 0.5959 - acc: 0.6706
Epoch 90/150
768/768 [==============================] - 0s 581us/step - loss: 0.5944 - acc: 0.6758
Epoch 91/150
768/768 [==============================] - 0s 535us/step - loss: 0.5929 - acc: 0.6719
Epoch 92/150
768/768 [==============================] - 0s 482us/step - loss: 0.5925 - acc: 0.6680
Epoch 93/150
768/768 [=

In [18]:
_, accuracy = model.evaluate(X, Y)

768/768 [==============================] - 0s 248us/step


In [19]:
print('Accuracy: %.2f' % (accuracy*100))

Accuracy: 70.31


In [26]:
Z = dataset[0:1,0:8]

In [27]:
Z

array([[  6.   , 148.   ,  72.   ,  35.   ,   0.   ,  33.6  ,   0.627,
         50.   ]])

In [28]:
predictions = model.predict_classes(Z)

In [29]:
predictions

array([[0]], dtype=int32)

In [34]:
K = dataset[2:3,0:8]

In [35]:
K

array([[  8.   , 183.   ,  64.   ,   0.   ,   0.   ,  23.3  ,   0.672,
         32.   ]])

In [38]:
predictions = model.predict_classes(K)

In [39]:
predictions

array([[0]], dtype=int32)