In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score
import numpy as np
import pandas as pd

In [2]:
from sklearn import datasets
cancer = datasets.load_breast_cancer()

In [3]:
X = cancer.data
y = cancer.target

In [4]:
X

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [6]:
model = LogisticRegression()
model.fit(X_train,y_train)

/home/nbuser/anaconda3_501/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [7]:
y_pred = model.predict(X_test)
y_pred

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0])

In [30]:
resultdf =  pd.DataFrame(y_test,columns=['test'])
resultdf['pred'] = y_pred
#resultdf['match'] = resultdf['pred'] == resultdf['test']
resultdf['match'] = if resultdf['pred'] == resultdf['test']): "True" else: "False"
resultdf

SyntaxError: invalid syntax (<ipython-input-30-6fa40db8aaaa>, line 4)

In [38]:
confusion_matrix(y_test,y_pred)

array([[39,  4],
       [ 1, 70]])

In [ ]:
TP            FP (type I)
FN (type II)  TN

In [40]:
accuracy_score(y_test,y_pred)

0.956140350877193

In [41]:
TP = 39
FP = 4
FN = 1 
TN = 70

In [47]:
total = TP + TN + FP + FN
total

114

In [48]:
accuracy = (TP+TN)/total
accuracy

0.956140350877193

In [49]:
error_rate = 1 - accuracy
error_rate

0.04385964912280704

In [50]:
# what portaion of possitive identifications was actually correct
# Precision means the percentage of your results which are relevant
# precision  = True Possitives / Actul results
precision = TP / (TP+FP)
precision

0.9069767441860465

In [51]:
# what portaion of actual possitives was identified correctly  
# recall refers to the percentage of total relevant results correctly classified by your algorithm
# precision  = True Possitives / Predicted results
recall = TP / (TP+FN)
recall

0.975