In [1]:
import numpy as np

In [2]:
input_data = np.array([2,3])
input_data

array([2, 3])

In [3]:
weights = {'node_0':np.array([1,1]),'node_1':np.array([-1,1]),'output':np.array([2,-1])}
weights

{'node_0': array([1, 1]), 'node_1': array([-1,  1]), 'output': array([ 2, -1])}

In [4]:
weights['node_0']

array([1, 1])

In [5]:
input_data * weights['node_0']

array([2, 3])

In [6]:
node_0_value = (input_data * weights['node_0']).sum()
node_0_value

5

In [7]:
node_1_value = (input_data * weights['node_1']).sum()
node_1_value

1

In [8]:
hidden_layer_values = np.array([node_0_value, node_1_value])
print(hidden_layer_values)

[5 1]


In [11]:
output = (hidden_layer_values * weights['output']).sum()
print(output)

9


In [12]:
node_0_input = (input_data * weights['node_0']).sum()
node_0_input

5

In [13]:
node_0_output = np.tanh(node_0_input)
node_0_output

0.9999092042625951

In [14]:
node_1_input = (input_data * weights['node_1']).sum()
node_1_input

1

In [15]:
node_1_output = np.tanh(node_1_input)
node_1_output

0.7615941559557649

In [16]:
hidden_layer_output = np.array([node_0_output,node_1_output])
hidden_layer_output

array([0.9999092 , 0.76159416])

In [17]:
output = (hidden_layer_output * weights['output']).sum()
print(output)

1.2382242525694254
