In [1]:
#scipy
import scipy
import numpy as np
from scipy import linalg

In [2]:
import operator
str1 = 'Python Programming'
substr = 'thon'
print(operator.contains(str1, substr))

True


In [5]:
A= np.array([[1,2],[3,4]])
B= np.array([[5],[6]])
A

array([[1, 2],
       [3, 4]])

In [4]:
B

array([[5],
       [6]])

In [6]:
X= linalg.solve(A,B)
X

array([[-4. ],
       [ 4.5]])

In [7]:
print(A.dot(X)-B)

[[0.]
 [0.]]


In [11]:
#2nd example
#1x + 2y =5
#3x + 4y =6
A= np.array([[1,2],[3,4]])
B= np.array([[5],[6]])
X= linalg.solve(A,B)
X

array([[-4. ],
       [ 4.5]])